name: CI

on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/**'

jobs:
  package:
    name: mvn package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: mvn package
        run: mvn package
